services:
  warp10:
    image: warp10io/warp10:2.11.1
    volumes:
      - warp10-data:/data
    ports:
      - 127.0.0.1:8080:8080
      - 127.0.0.1:8081:8081

  crawler:
    build: .
    environment:
      - TWITCH_CLIENT_ID=$TWITCH_CLIENT_ID
      - TWITCH_CLIENT_SECRET=$TWITCH_CLIENT_SECRET
      - WARP10_URL=http://warp10:8080
      - WARP10_WRITE_TOKEN=$WARP10_WRITE_TOKEN
      - EVENT_NAME=optlol
      - USER_LOGINS=otplol_
    links:
      - warp10

volumes:
  warp10-data:
